//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSTM.Business.CourseServiceMethod {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SSTMSoap", Namespace="http://tempuri.org/")]
    public partial class SSTM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AllCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllCourseTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllCourseLevelOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllTrainerOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodayCoursesWithSectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodayCoursesWithSectionTaineridOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodayCoursesOnlyTrainerOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemorandomPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemorandomPathJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodayCoursesOnlyTrainerJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodayCoursesWithSectionJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllCourseJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllTrainerJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllSTudentstodaystartclassINTROPAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllcourseandbatchidTodaystartclassINTROPAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodayStudemtidForDEviceINTROPAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrainerDetailsINTROPAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentdatawithcourseandbatchINTROPAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrainerIndustryEXPINTROPAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback CourseProposalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewcourseInLIOperationCompleted;
        
        private System.Threading.SendOrPostCallback NeedAnalysisOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SSTM() {
            this.Url = global::SSTM.Business.Properties.Settings.Default.SSTM_Business_CourseServiceMethod_SSTM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AllCourseCompletedEventHandler AllCourseCompleted;
        
        /// <remarks/>
        public event AllCourseTypeCompletedEventHandler AllCourseTypeCompleted;
        
        /// <remarks/>
        public event AllCourseLevelCompletedEventHandler AllCourseLevelCompleted;
        
        /// <remarks/>
        public event AllTrainerCompletedEventHandler AllTrainerCompleted;
        
        /// <remarks/>
        public event TodayCoursesWithSectionCompletedEventHandler TodayCoursesWithSectionCompleted;
        
        /// <remarks/>
        public event TodayCoursesWithSectionTaineridCompletedEventHandler TodayCoursesWithSectionTaineridCompleted;
        
        /// <remarks/>
        public event TodayCoursesOnlyTrainerCompletedEventHandler TodayCoursesOnlyTrainerCompleted;
        
        /// <remarks/>
        public event MemorandomPathCompletedEventHandler MemorandomPathCompleted;
        
        /// <remarks/>
        public event MemorandomPathJSONCompletedEventHandler MemorandomPathJSONCompleted;
        
        /// <remarks/>
        public event TodayCoursesOnlyTrainerJSONCompletedEventHandler TodayCoursesOnlyTrainerJSONCompleted;
        
        /// <remarks/>
        public event TodayCoursesWithSectionJSONCompletedEventHandler TodayCoursesWithSectionJSONCompleted;
        
        /// <remarks/>
        public event AllCourseJSONCompletedEventHandler AllCourseJSONCompleted;
        
        /// <remarks/>
        public event AllTrainerJSONCompletedEventHandler AllTrainerJSONCompleted;
        
        /// <remarks/>
        public event AllSTudentstodaystartclassINTROPAGECompletedEventHandler AllSTudentstodaystartclassINTROPAGECompleted;
        
        /// <remarks/>
        public event AllcourseandbatchidTodaystartclassINTROPAGECompletedEventHandler AllcourseandbatchidTodaystartclassINTROPAGECompleted;
        
        /// <remarks/>
        public event TodayStudemtidForDEviceINTROPAGECompletedEventHandler TodayStudemtidForDEviceINTROPAGECompleted;
        
        /// <remarks/>
        public event TrainerDetailsINTROPAGECompletedEventHandler TrainerDetailsINTROPAGECompleted;
        
        /// <remarks/>
        public event StudentdatawithcourseandbatchINTROPAGECompletedEventHandler StudentdatawithcourseandbatchINTROPAGECompleted;
        
        /// <remarks/>
        public event TrainerIndustryEXPINTROPAGECompletedEventHandler TrainerIndustryEXPINTROPAGECompleted;
        
        /// <remarks/>
        public event CourseProposalCompletedEventHandler CourseProposalCompleted;
        
        /// <remarks/>
        public event AddNewcourseInLICompletedEventHandler AddNewcourseInLICompleted;
        
        /// <remarks/>
        public event NeedAnalysisCompletedEventHandler NeedAnalysisCompleted;
        
        /// <remarks/>
        public event GameCompletedEventHandler GameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllCourse() {
            object[] results = this.Invoke("AllCourse", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AllCourseAsync() {
            this.AllCourseAsync(null);
        }
        
        /// <remarks/>
        public void AllCourseAsync(object userState) {
            if ((this.AllCourseOperationCompleted == null)) {
                this.AllCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllCourseOperationCompleted);
            }
            this.InvokeAsync("AllCourse", new object[0], this.AllCourseOperationCompleted, userState);
        }
        
        private void OnAllCourseOperationCompleted(object arg) {
            if ((this.AllCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllCourseCompleted(this, new AllCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllCourseType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllCourseType() {
            object[] results = this.Invoke("AllCourseType", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AllCourseTypeAsync() {
            this.AllCourseTypeAsync(null);
        }
        
        /// <remarks/>
        public void AllCourseTypeAsync(object userState) {
            if ((this.AllCourseTypeOperationCompleted == null)) {
                this.AllCourseTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllCourseTypeOperationCompleted);
            }
            this.InvokeAsync("AllCourseType", new object[0], this.AllCourseTypeOperationCompleted, userState);
        }
        
        private void OnAllCourseTypeOperationCompleted(object arg) {
            if ((this.AllCourseTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllCourseTypeCompleted(this, new AllCourseTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllCourseLevel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllCourseLevel() {
            object[] results = this.Invoke("AllCourseLevel", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AllCourseLevelAsync() {
            this.AllCourseLevelAsync(null);
        }
        
        /// <remarks/>
        public void AllCourseLevelAsync(object userState) {
            if ((this.AllCourseLevelOperationCompleted == null)) {
                this.AllCourseLevelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllCourseLevelOperationCompleted);
            }
            this.InvokeAsync("AllCourseLevel", new object[0], this.AllCourseLevelOperationCompleted, userState);
        }
        
        private void OnAllCourseLevelOperationCompleted(object arg) {
            if ((this.AllCourseLevelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllCourseLevelCompleted(this, new AllCourseLevelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllTrainer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllTrainer() {
            object[] results = this.Invoke("AllTrainer", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AllTrainerAsync() {
            this.AllTrainerAsync(null);
        }
        
        /// <remarks/>
        public void AllTrainerAsync(object userState) {
            if ((this.AllTrainerOperationCompleted == null)) {
                this.AllTrainerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllTrainerOperationCompleted);
            }
            this.InvokeAsync("AllTrainer", new object[0], this.AllTrainerOperationCompleted, userState);
        }
        
        private void OnAllTrainerOperationCompleted(object arg) {
            if ((this.AllTrainerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllTrainerCompleted(this, new AllTrainerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodayCoursesWithSection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TodayCoursesWithSection(string date) {
            object[] results = this.Invoke("TodayCoursesWithSection", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TodayCoursesWithSectionAsync(string date) {
            this.TodayCoursesWithSectionAsync(date, null);
        }
        
        /// <remarks/>
        public void TodayCoursesWithSectionAsync(string date, object userState) {
            if ((this.TodayCoursesWithSectionOperationCompleted == null)) {
                this.TodayCoursesWithSectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodayCoursesWithSectionOperationCompleted);
            }
            this.InvokeAsync("TodayCoursesWithSection", new object[] {
                        date}, this.TodayCoursesWithSectionOperationCompleted, userState);
        }
        
        private void OnTodayCoursesWithSectionOperationCompleted(object arg) {
            if ((this.TodayCoursesWithSectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodayCoursesWithSectionCompleted(this, new TodayCoursesWithSectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodayCoursesWithSectionTainerid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TodayCoursesWithSectionTainerid(string date, int trainerid) {
            object[] results = this.Invoke("TodayCoursesWithSectionTainerid", new object[] {
                        date,
                        trainerid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TodayCoursesWithSectionTaineridAsync(string date, int trainerid) {
            this.TodayCoursesWithSectionTaineridAsync(date, trainerid, null);
        }
        
        /// <remarks/>
        public void TodayCoursesWithSectionTaineridAsync(string date, int trainerid, object userState) {
            if ((this.TodayCoursesWithSectionTaineridOperationCompleted == null)) {
                this.TodayCoursesWithSectionTaineridOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodayCoursesWithSectionTaineridOperationCompleted);
            }
            this.InvokeAsync("TodayCoursesWithSectionTainerid", new object[] {
                        date,
                        trainerid}, this.TodayCoursesWithSectionTaineridOperationCompleted, userState);
        }
        
        private void OnTodayCoursesWithSectionTaineridOperationCompleted(object arg) {
            if ((this.TodayCoursesWithSectionTaineridCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodayCoursesWithSectionTaineridCompleted(this, new TodayCoursesWithSectionTaineridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodayCoursesOnlyTrainer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TodayCoursesOnlyTrainer(string date) {
            object[] results = this.Invoke("TodayCoursesOnlyTrainer", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TodayCoursesOnlyTrainerAsync(string date) {
            this.TodayCoursesOnlyTrainerAsync(date, null);
        }
        
        /// <remarks/>
        public void TodayCoursesOnlyTrainerAsync(string date, object userState) {
            if ((this.TodayCoursesOnlyTrainerOperationCompleted == null)) {
                this.TodayCoursesOnlyTrainerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodayCoursesOnlyTrainerOperationCompleted);
            }
            this.InvokeAsync("TodayCoursesOnlyTrainer", new object[] {
                        date}, this.TodayCoursesOnlyTrainerOperationCompleted, userState);
        }
        
        private void OnTodayCoursesOnlyTrainerOperationCompleted(object arg) {
            if ((this.TodayCoursesOnlyTrainerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodayCoursesOnlyTrainerCompleted(this, new TodayCoursesOnlyTrainerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemorandomPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MemorandomPath() {
            object[] results = this.Invoke("MemorandomPath", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MemorandomPathAsync() {
            this.MemorandomPathAsync(null);
        }
        
        /// <remarks/>
        public void MemorandomPathAsync(object userState) {
            if ((this.MemorandomPathOperationCompleted == null)) {
                this.MemorandomPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemorandomPathOperationCompleted);
            }
            this.InvokeAsync("MemorandomPath", new object[0], this.MemorandomPathOperationCompleted, userState);
        }
        
        private void OnMemorandomPathOperationCompleted(object arg) {
            if ((this.MemorandomPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemorandomPathCompleted(this, new MemorandomPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemorandomPathJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MemorandomPathJSON() {
            this.Invoke("MemorandomPathJSON", new object[0]);
        }
        
        /// <remarks/>
        public void MemorandomPathJSONAsync() {
            this.MemorandomPathJSONAsync(null);
        }
        
        /// <remarks/>
        public void MemorandomPathJSONAsync(object userState) {
            if ((this.MemorandomPathJSONOperationCompleted == null)) {
                this.MemorandomPathJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemorandomPathJSONOperationCompleted);
            }
            this.InvokeAsync("MemorandomPathJSON", new object[0], this.MemorandomPathJSONOperationCompleted, userState);
        }
        
        private void OnMemorandomPathJSONOperationCompleted(object arg) {
            if ((this.MemorandomPathJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemorandomPathJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodayCoursesOnlyTrainerJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TodayCoursesOnlyTrainerJSON(string date) {
            this.Invoke("TodayCoursesOnlyTrainerJSON", new object[] {
                        date});
        }
        
        /// <remarks/>
        public void TodayCoursesOnlyTrainerJSONAsync(string date) {
            this.TodayCoursesOnlyTrainerJSONAsync(date, null);
        }
        
        /// <remarks/>
        public void TodayCoursesOnlyTrainerJSONAsync(string date, object userState) {
            if ((this.TodayCoursesOnlyTrainerJSONOperationCompleted == null)) {
                this.TodayCoursesOnlyTrainerJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodayCoursesOnlyTrainerJSONOperationCompleted);
            }
            this.InvokeAsync("TodayCoursesOnlyTrainerJSON", new object[] {
                        date}, this.TodayCoursesOnlyTrainerJSONOperationCompleted, userState);
        }
        
        private void OnTodayCoursesOnlyTrainerJSONOperationCompleted(object arg) {
            if ((this.TodayCoursesOnlyTrainerJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodayCoursesOnlyTrainerJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodayCoursesWithSectionJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TodayCoursesWithSectionJSON(string date) {
            this.Invoke("TodayCoursesWithSectionJSON", new object[] {
                        date});
        }
        
        /// <remarks/>
        public void TodayCoursesWithSectionJSONAsync(string date) {
            this.TodayCoursesWithSectionJSONAsync(date, null);
        }
        
        /// <remarks/>
        public void TodayCoursesWithSectionJSONAsync(string date, object userState) {
            if ((this.TodayCoursesWithSectionJSONOperationCompleted == null)) {
                this.TodayCoursesWithSectionJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodayCoursesWithSectionJSONOperationCompleted);
            }
            this.InvokeAsync("TodayCoursesWithSectionJSON", new object[] {
                        date}, this.TodayCoursesWithSectionJSONOperationCompleted, userState);
        }
        
        private void OnTodayCoursesWithSectionJSONOperationCompleted(object arg) {
            if ((this.TodayCoursesWithSectionJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodayCoursesWithSectionJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllCourseJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AllCourseJSON() {
            this.Invoke("AllCourseJSON", new object[0]);
        }
        
        /// <remarks/>
        public void AllCourseJSONAsync() {
            this.AllCourseJSONAsync(null);
        }
        
        /// <remarks/>
        public void AllCourseJSONAsync(object userState) {
            if ((this.AllCourseJSONOperationCompleted == null)) {
                this.AllCourseJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllCourseJSONOperationCompleted);
            }
            this.InvokeAsync("AllCourseJSON", new object[0], this.AllCourseJSONOperationCompleted, userState);
        }
        
        private void OnAllCourseJSONOperationCompleted(object arg) {
            if ((this.AllCourseJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllCourseJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllTrainerJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AllTrainerJSON() {
            this.Invoke("AllTrainerJSON", new object[0]);
        }
        
        /// <remarks/>
        public void AllTrainerJSONAsync() {
            this.AllTrainerJSONAsync(null);
        }
        
        /// <remarks/>
        public void AllTrainerJSONAsync(object userState) {
            if ((this.AllTrainerJSONOperationCompleted == null)) {
                this.AllTrainerJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllTrainerJSONOperationCompleted);
            }
            this.InvokeAsync("AllTrainerJSON", new object[0], this.AllTrainerJSONOperationCompleted, userState);
        }
        
        private void OnAllTrainerJSONOperationCompleted(object arg) {
            if ((this.AllTrainerJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllTrainerJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllSTudentstodaystartclassINTROPAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AllSTudentstodaystartclassINTROPAGE() {
            this.Invoke("AllSTudentstodaystartclassINTROPAGE", new object[0]);
        }
        
        /// <remarks/>
        public void AllSTudentstodaystartclassINTROPAGEAsync() {
            this.AllSTudentstodaystartclassINTROPAGEAsync(null);
        }
        
        /// <remarks/>
        public void AllSTudentstodaystartclassINTROPAGEAsync(object userState) {
            if ((this.AllSTudentstodaystartclassINTROPAGEOperationCompleted == null)) {
                this.AllSTudentstodaystartclassINTROPAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllSTudentstodaystartclassINTROPAGEOperationCompleted);
            }
            this.InvokeAsync("AllSTudentstodaystartclassINTROPAGE", new object[0], this.AllSTudentstodaystartclassINTROPAGEOperationCompleted, userState);
        }
        
        private void OnAllSTudentstodaystartclassINTROPAGEOperationCompleted(object arg) {
            if ((this.AllSTudentstodaystartclassINTROPAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllSTudentstodaystartclassINTROPAGECompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllcourseandbatchidTodaystartclassINTROPAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AllcourseandbatchidTodaystartclassINTROPAGE() {
            this.Invoke("AllcourseandbatchidTodaystartclassINTROPAGE", new object[0]);
        }
        
        /// <remarks/>
        public void AllcourseandbatchidTodaystartclassINTROPAGEAsync() {
            this.AllcourseandbatchidTodaystartclassINTROPAGEAsync(null);
        }
        
        /// <remarks/>
        public void AllcourseandbatchidTodaystartclassINTROPAGEAsync(object userState) {
            if ((this.AllcourseandbatchidTodaystartclassINTROPAGEOperationCompleted == null)) {
                this.AllcourseandbatchidTodaystartclassINTROPAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllcourseandbatchidTodaystartclassINTROPAGEOperationCompleted);
            }
            this.InvokeAsync("AllcourseandbatchidTodaystartclassINTROPAGE", new object[0], this.AllcourseandbatchidTodaystartclassINTROPAGEOperationCompleted, userState);
        }
        
        private void OnAllcourseandbatchidTodaystartclassINTROPAGEOperationCompleted(object arg) {
            if ((this.AllcourseandbatchidTodaystartclassINTROPAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllcourseandbatchidTodaystartclassINTROPAGECompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TodayStudemtidForDEviceINTROPAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TodayStudemtidForDEviceINTROPAGE(int studentid) {
            object[] results = this.Invoke("TodayStudemtidForDEviceINTROPAGE", new object[] {
                        studentid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TodayStudemtidForDEviceINTROPAGEAsync(int studentid) {
            this.TodayStudemtidForDEviceINTROPAGEAsync(studentid, null);
        }
        
        /// <remarks/>
        public void TodayStudemtidForDEviceINTROPAGEAsync(int studentid, object userState) {
            if ((this.TodayStudemtidForDEviceINTROPAGEOperationCompleted == null)) {
                this.TodayStudemtidForDEviceINTROPAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodayStudemtidForDEviceINTROPAGEOperationCompleted);
            }
            this.InvokeAsync("TodayStudemtidForDEviceINTROPAGE", new object[] {
                        studentid}, this.TodayStudemtidForDEviceINTROPAGEOperationCompleted, userState);
        }
        
        private void OnTodayStudemtidForDEviceINTROPAGEOperationCompleted(object arg) {
            if ((this.TodayStudemtidForDEviceINTROPAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodayStudemtidForDEviceINTROPAGECompleted(this, new TodayStudemtidForDEviceINTROPAGECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrainerDetailsINTROPAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TrainerDetailsINTROPAGE(int courseid, float batchid, string Todaydate) {
            this.Invoke("TrainerDetailsINTROPAGE", new object[] {
                        courseid,
                        batchid,
                        Todaydate});
        }
        
        /// <remarks/>
        public void TrainerDetailsINTROPAGEAsync(int courseid, float batchid, string Todaydate) {
            this.TrainerDetailsINTROPAGEAsync(courseid, batchid, Todaydate, null);
        }
        
        /// <remarks/>
        public void TrainerDetailsINTROPAGEAsync(int courseid, float batchid, string Todaydate, object userState) {
            if ((this.TrainerDetailsINTROPAGEOperationCompleted == null)) {
                this.TrainerDetailsINTROPAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrainerDetailsINTROPAGEOperationCompleted);
            }
            this.InvokeAsync("TrainerDetailsINTROPAGE", new object[] {
                        courseid,
                        batchid,
                        Todaydate}, this.TrainerDetailsINTROPAGEOperationCompleted, userState);
        }
        
        private void OnTrainerDetailsINTROPAGEOperationCompleted(object arg) {
            if ((this.TrainerDetailsINTROPAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrainerDetailsINTROPAGECompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentdatawithcourseandbatchINTROPAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StudentdatawithcourseandbatchINTROPAGE(int courseid, float batchid) {
            this.Invoke("StudentdatawithcourseandbatchINTROPAGE", new object[] {
                        courseid,
                        batchid});
        }
        
        /// <remarks/>
        public void StudentdatawithcourseandbatchINTROPAGEAsync(int courseid, float batchid) {
            this.StudentdatawithcourseandbatchINTROPAGEAsync(courseid, batchid, null);
        }
        
        /// <remarks/>
        public void StudentdatawithcourseandbatchINTROPAGEAsync(int courseid, float batchid, object userState) {
            if ((this.StudentdatawithcourseandbatchINTROPAGEOperationCompleted == null)) {
                this.StudentdatawithcourseandbatchINTROPAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentdatawithcourseandbatchINTROPAGEOperationCompleted);
            }
            this.InvokeAsync("StudentdatawithcourseandbatchINTROPAGE", new object[] {
                        courseid,
                        batchid}, this.StudentdatawithcourseandbatchINTROPAGEOperationCompleted, userState);
        }
        
        private void OnStudentdatawithcourseandbatchINTROPAGEOperationCompleted(object arg) {
            if ((this.StudentdatawithcourseandbatchINTROPAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentdatawithcourseandbatchINTROPAGECompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrainerIndustryEXPINTROPAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TrainerIndustryEXPINTROPAGE(int trainerid) {
            this.Invoke("TrainerIndustryEXPINTROPAGE", new object[] {
                        trainerid});
        }
        
        /// <remarks/>
        public void TrainerIndustryEXPINTROPAGEAsync(int trainerid) {
            this.TrainerIndustryEXPINTROPAGEAsync(trainerid, null);
        }
        
        /// <remarks/>
        public void TrainerIndustryEXPINTROPAGEAsync(int trainerid, object userState) {
            if ((this.TrainerIndustryEXPINTROPAGEOperationCompleted == null)) {
                this.TrainerIndustryEXPINTROPAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrainerIndustryEXPINTROPAGEOperationCompleted);
            }
            this.InvokeAsync("TrainerIndustryEXPINTROPAGE", new object[] {
                        trainerid}, this.TrainerIndustryEXPINTROPAGEOperationCompleted, userState);
        }
        
        private void OnTrainerIndustryEXPINTROPAGEOperationCompleted(object arg) {
            if ((this.TrainerIndustryEXPINTROPAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrainerIndustryEXPINTROPAGECompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CourseProposal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CourseProposal() {
            object[] results = this.Invoke("CourseProposal", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CourseProposalAsync() {
            this.CourseProposalAsync(null);
        }
        
        /// <remarks/>
        public void CourseProposalAsync(object userState) {
            if ((this.CourseProposalOperationCompleted == null)) {
                this.CourseProposalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCourseProposalOperationCompleted);
            }
            this.InvokeAsync("CourseProposal", new object[0], this.CourseProposalOperationCompleted, userState);
        }
        
        private void OnCourseProposalOperationCompleted(object arg) {
            if ((this.CourseProposalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CourseProposalCompleted(this, new CourseProposalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewcourseInLI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddNewcourseInLI(string Coursename, int Departmentid) {
            object[] results = this.Invoke("AddNewcourseInLI", new object[] {
                        Coursename,
                        Departmentid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewcourseInLIAsync(string Coursename, int Departmentid) {
            this.AddNewcourseInLIAsync(Coursename, Departmentid, null);
        }
        
        /// <remarks/>
        public void AddNewcourseInLIAsync(string Coursename, int Departmentid, object userState) {
            if ((this.AddNewcourseInLIOperationCompleted == null)) {
                this.AddNewcourseInLIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewcourseInLIOperationCompleted);
            }
            this.InvokeAsync("AddNewcourseInLI", new object[] {
                        Coursename,
                        Departmentid}, this.AddNewcourseInLIOperationCompleted, userState);
        }
        
        private void OnAddNewcourseInLIOperationCompleted(object arg) {
            if ((this.AddNewcourseInLICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewcourseInLICompleted(this, new AddNewcourseInLICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NeedAnalysis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NeedAnalysis() {
            object[] results = this.Invoke("NeedAnalysis", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NeedAnalysisAsync() {
            this.NeedAnalysisAsync(null);
        }
        
        /// <remarks/>
        public void NeedAnalysisAsync(object userState) {
            if ((this.NeedAnalysisOperationCompleted == null)) {
                this.NeedAnalysisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNeedAnalysisOperationCompleted);
            }
            this.InvokeAsync("NeedAnalysis", new object[0], this.NeedAnalysisOperationCompleted, userState);
        }
        
        private void OnNeedAnalysisOperationCompleted(object arg) {
            if ((this.NeedAnalysisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NeedAnalysisCompleted(this, new NeedAnalysisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Game", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Game(int studentid, string GameName, float Marks, string File) {
            object[] results = this.Invoke("Game", new object[] {
                        studentid,
                        GameName,
                        Marks,
                        File});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GameAsync(int studentid, string GameName, float Marks, string File) {
            this.GameAsync(studentid, GameName, Marks, File, null);
        }
        
        /// <remarks/>
        public void GameAsync(int studentid, string GameName, float Marks, string File, object userState) {
            if ((this.GameOperationCompleted == null)) {
                this.GameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameOperationCompleted);
            }
            this.InvokeAsync("Game", new object[] {
                        studentid,
                        GameName,
                        Marks,
                        File}, this.GameOperationCompleted, userState);
        }
        
        private void OnGameOperationCompleted(object arg) {
            if ((this.GameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameCompleted(this, new GameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllCourseCompletedEventHandler(object sender, AllCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllCourseTypeCompletedEventHandler(object sender, AllCourseTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllCourseTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllCourseTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllCourseLevelCompletedEventHandler(object sender, AllCourseLevelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllCourseLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllCourseLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllTrainerCompletedEventHandler(object sender, AllTrainerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllTrainerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllTrainerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TodayCoursesWithSectionCompletedEventHandler(object sender, TodayCoursesWithSectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodayCoursesWithSectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodayCoursesWithSectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TodayCoursesWithSectionTaineridCompletedEventHandler(object sender, TodayCoursesWithSectionTaineridCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodayCoursesWithSectionTaineridCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodayCoursesWithSectionTaineridCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TodayCoursesOnlyTrainerCompletedEventHandler(object sender, TodayCoursesOnlyTrainerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodayCoursesOnlyTrainerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodayCoursesOnlyTrainerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MemorandomPathCompletedEventHandler(object sender, MemorandomPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemorandomPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemorandomPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MemorandomPathJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TodayCoursesOnlyTrainerJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TodayCoursesWithSectionJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllCourseJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllTrainerJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllSTudentstodaystartclassINTROPAGECompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AllcourseandbatchidTodaystartclassINTROPAGECompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TodayStudemtidForDEviceINTROPAGECompletedEventHandler(object sender, TodayStudemtidForDEviceINTROPAGECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodayStudemtidForDEviceINTROPAGECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodayStudemtidForDEviceINTROPAGECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TrainerDetailsINTROPAGECompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void StudentdatawithcourseandbatchINTROPAGECompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TrainerIndustryEXPINTROPAGECompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CourseProposalCompletedEventHandler(object sender, CourseProposalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CourseProposalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CourseProposalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddNewcourseInLICompletedEventHandler(object sender, AddNewcourseInLICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewcourseInLICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewcourseInLICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void NeedAnalysisCompletedEventHandler(object sender, NeedAnalysisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NeedAnalysisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NeedAnalysisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GameCompletedEventHandler(object sender, GameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591